// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRr-g1pkTQvHC5_YSb96WKDa54nseg1Q',
    appId: '1:865362398009:web:5b92cf9b4a5726536376e8',
    messagingSenderId: '865362398009',
    projectId: 'fir-f1450',
    authDomain: 'fir-f1450.firebaseapp.com',
    storageBucket: 'fir-f1450.firebasestorage.app',
    measurementId: 'G-DMRYFGT81W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBGbTicV8x66woFqOmpFyRhSbD_ty3PE',
    appId: '1:865362398009:android:c733e9197c8cff356376e8',
    messagingSenderId: '865362398009',
    projectId: 'fir-f1450',
    storageBucket: 'fir-f1450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUaA-bKcIErUC8uQelSoqu08zte6dKpO4',
    appId: '1:865362398009:ios:4a7732759c887fe66376e8',
    messagingSenderId: '865362398009',
    projectId: 'fir-f1450',
    storageBucket: 'fir-f1450.firebasestorage.app',
    iosBundleId: 'com.example.itiCu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUaA-bKcIErUC8uQelSoqu08zte6dKpO4',
    appId: '1:865362398009:ios:4a7732759c887fe66376e8',
    messagingSenderId: '865362398009',
    projectId: 'fir-f1450',
    storageBucket: 'fir-f1450.firebasestorage.app',
    iosBundleId: 'com.example.itiCu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkRr-g1pkTQvHC5_YSb96WKDa54nseg1Q',
    appId: '1:865362398009:web:33c257c17998df676376e8',
    messagingSenderId: '865362398009',
    projectId: 'fir-f1450',
    authDomain: 'fir-f1450.firebaseapp.com',
    storageBucket: 'fir-f1450.firebasestorage.app',
    measurementId: 'G-B5JSHYJF5G',
  );
}
