// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBeKJU4-ru2liXJ4k6hbNxyuHNoI3PiSM',
    appId: '1:649683202154:web:ec951df93c7bd0d13fda13',
    messagingSenderId: '649683202154',
    projectId: 'chatapp-2fcb9',
    authDomain: 'chatapp-2fcb9.firebaseapp.com',
    storageBucket: 'chatapp-2fcb9.firebasestorage.app',
    measurementId: 'G-6P9QZLP6KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9nlGR84xjVPloIJrP_MMLEECdo61lAbc',
    appId: '1:649683202154:android:4e0b675d11766c4c3fda13',
    messagingSenderId: '649683202154',
    projectId: 'chatapp-2fcb9',
    storageBucket: 'chatapp-2fcb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VJe8wvguL7vd3N_P3mBKfjExFbf9XHs',
    appId: '1:649683202154:ios:0cffafb22e4a33f43fda13',
    messagingSenderId: '649683202154',
    projectId: 'chatapp-2fcb9',
    storageBucket: 'chatapp-2fcb9.firebasestorage.app',
    iosBundleId: 'com.example.itiCu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4VJe8wvguL7vd3N_P3mBKfjExFbf9XHs',
    appId: '1:649683202154:ios:0cffafb22e4a33f43fda13',
    messagingSenderId: '649683202154',
    projectId: 'chatapp-2fcb9',
    storageBucket: 'chatapp-2fcb9.firebasestorage.app',
    iosBundleId: 'com.example.itiCu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBeKJU4-ru2liXJ4k6hbNxyuHNoI3PiSM',
    appId: '1:649683202154:web:ac670220b51f05803fda13',
    messagingSenderId: '649683202154',
    projectId: 'chatapp-2fcb9',
    authDomain: 'chatapp-2fcb9.firebaseapp.com',
    storageBucket: 'chatapp-2fcb9.firebasestorage.app',
    measurementId: 'G-32TYM2JMQB',
  );
}
